### ISSUE TITLE
Create site from PSD

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#1]
The PSD is in the google drive
Hand-coded site

Please have something pushed to gh-pages by 12-2-15   10a

due:
12-6-15

**Comment by jperez4509** [comment]
@rodneystrong http://editllc.github.io/client-estate-research/

**Comment by rodneystrong** [comment]
Good stuff Joel. Just emailed client with the URL. Thanks for maintaining consistent progress.

**Comment by jperez4509** [comment]
Home page is complete and fully responsive. http://editllc.github.io/client-estate-research/

**Comment by jperez4509** [comment]
done.
