### ISSUE TITLE
Bottom Testimonials section

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#10]
Remove this from the actual "Testimonials" page. No need to have both. 

Also, remove the slider code, make it so only one testimonial displays on each page. Specifically: 

Home page: # 46
About us:  # 41
Credentials:  # 21
Contact us: # 8

Refer to this Google doc to understand the above: https://drive.google.com/drive/folders/0B2lLrPKhGIbrbS1MNzQzVDI3UUE

due:
12-16-15   5p

updated due:
12-20-15  5p

**Comment by rampage1213** [comment]
@rodneystrong Pushing the deadline to 12-16-15 6p

**Comment by rampage1213** [comment]
@rodneystrong: For the quotes on the google drive there is only 40 quotes and 40 images so the home and about us pages are in need of quotes

**Comment by rodneystrong** [comment]
I've emailed the client for instructions on this. applying the appropriate label.

**Comment by rodneystrong** [comment]
Heard back from client: 

> Please use the following:
 
Home page – 40   (This is the quote # and the corresponding PDF Exhibit #.)
About Us – 34
Credentials – 19
Contact us - 5
 
Thanks,
 
 
Paul Elissiry


due: 
12-20-15  5p

**Comment by rampage1213** [comment]
Done!
