### ISSUE TITLE
Footer for whole site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#11]
Delete the map. Replace it with the BBB Seal.

>I looked at our BBB account and see that we have access to several different seal versions and sizes. You can download them here: http://www.bbb.org/greater-san-francisco/logo-linking/  you will need to input our account number of 36315.
 I like the seals showing our rating, such as:

Use this code to display the BBB seal: <a class="erhzbum" href="http://www.bbb.org/greater-san-francisco/business-reviews/investigators/estate-research-associates-in-san-ramon-ca-36315#bbbseal" title="Estate Research Associates, Inc. is a BBB Accredited Investigator in San Ramon, CA" style="display: block;position: relative;overflow: hidden; width: 250px; height: 52px; margin: 0px; padding: 0px;"><img style="padding: 0px; border: none;" src="http://seal-goldengate.bbb.org/logo/erhzbum/estate-research-associates-36315.png" width="250" height="52" alt="Estate Research Associates, Inc. is a BBB Accredited Investigator in San Ramon, CA" /></a>

Move the email address for the business to be below the BBB seal.

due:
12-16-15   5p

**Comment by rampage1213** [comment]
Done!
