### ISSUE TITLE
Replace the logo

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#12]
Replace the logo with the one Joel made in issue #3 

If you can't find it, it should be on our google drive as well. If it isn't in our google drive, bug @jperez4509 

due:
12-26-15   4p

**Comment by rampage1213** [comment]
Something came up will get this done 12/27/15 11pm

**Comment by jperez4509** [comment]
@rampage1213 @rodneystrong  I have created a new folder in the assets folder for the client. There you will find an ai, png, and a pdf. https://drive.google.com/folderview?id=0B0GRwzxO60XiM2p2TUgxSkxnalk&usp=sharing

**Comment by rampage1213** [comment]
Done!
