### ISSUE TITLE
Change the "Credentials" page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#13]
https://drive.google.com/open?id=0B2lLrPKhGIbrdXpZUzRfV050LTA

To look like the google doc linked above. You should be able to find the individual assets that google doc references in the "credentials page" folder in the same folder. Careful, be sure you follow the doc I linked above which is titled "credentials page to buildicus v2", because there is another doc in the folder called "credentials page to buildicus v1". 

due:
12-26-15    5p

**Comment by rampage1213** [comment]
Something came up will get this done 12/27/15 11pm

**Comment by rampage1213** [comment]
Done

**Comment by rodneystrong** [comment]
good job dude. all instructions were followed.
