### ISSUE TITLE
Contact us Page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#14]
Delete this line:
Please call us at 1-800-245-3285 if you have any questions about our firm or your case.

To the right of the address, put a photo of the building  

Under the photo of the building, put the street map.  (because the map is no longer in the footer.)

The photo of the building should be in the google drive. You'll know it when you see it. I'm purposefully not telling you how to display it because I want you to decide how it will best look. This is a small choice so don't fret, just decide and go with it. I'll either not like it and offer a suggestion or love it. 

due:
12-26-15  5p

**Comment by rampage1213** [comment]
Something came up will get this done 12/27/15 11pm

**Comment by rampage1213** [comment]
Done

**Comment by rodneystrong** [comment]
well done
