### ISSUE TITLE
Testimonial Page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#17]
>We like the collage appearance; however we feel a conservative list would work better with the age group we typically work with (age 60+ for most heirs).

Please change it to one long list.
Use the same format as the footer of the other pages: Quote on the left and image on the right.

Reverse chronological order -- 2015 first...1989 at the bottom.

Make the text black.  
Use a white background

due:
12-28-15    5p

updated due:
1-2-16  3p

**Comment by rampage1213** [comment]
Almost done with this I will need to push the deadline to 12-28-15 12am

**Comment by rampage1213** [comment]
Done

**Comment by rodneystrong** [comment]
You forgot to make the top heading black  -__-)

**Comment by rodneystrong** [comment]
updated due:
1-2-15   3p

**Comment by rampage1213** [comment]
Done!
