### ISSUE TITLE
Remove the "Exhibit" stamp from all the testimonial images

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#18]
This is gonna be tedious.. Ask @jperez4509 for a possible tip on how to do this quickly or just split the task with him if need be. 

All the testimonial letters have an "Exhibit" stamp on them (e.g. "exhibit 12"). We need to remove all those exhibit stamps and then re-upload the letters.

due:
12-28-15 6p

**Comment by rampage1213** [comment]
Done!
