### ISSUE TITLE
Content udpate #1

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#2]
Hi Alex:
 
Thanks for the update.  Please note the following items:
 
·        We will have five pages for now:

o   Home Page

o   About Us

o   Credentials

o   Testimonials

o   Contact Us

 

·        The content and design notes for all five pages are contained in the shared drive, subfolder: Content Files ERA to Biuildicus. Please do not use the WORD file dated 11/20/2015 in the root folder because that file is replaced by the individual files in the subfolder as follows:

 

 
·        The PSD file is for the graphics design of the top map only – the content on the PSD can be ignored.  The content for the Home page, and changes needed to the design, are listed in the Home Page WORD Doc. (I will forward an email I sent to Richard before you were onboard regarding the PSD file.)

 

·        For the graphics on the top of each page (the map), please make it take up a small portion of the screen – perhaps ¼ or so.  It is OK if the page does not take the entire width of the screen (not sure what you call that style). The borders on the right and left could be a rich color to match the page.

 

If you have any questions or need clarification, please call me anytime at 925-743-9700.
 
I hope you have a nice weekend.  Thank you for your work – much appreciated!

due:
12-9-15   3p

**Comment by jperez4509** [comment]
I have redone the home page according to the word document instead of the PSD. Here is the link: http://editllc.github.io/client-estate-research/ . Hoping to complete the other pages today.

**Comment by rodneystrong** [comment]
Good stuff

**Comment by jperez4509** [comment]
I have complete most of the pages for the site. Do I add a contact form using woofoo forms or is the current contact page okay? http://editllc.github.io/client-estate-research/contact-index.html . I am also thinking of doing a masonry for the testimonials page because on their notes they mention they want quotes and a lightbox affect that shows the original letter they scanned. I will be working on that today.

**Comment by jperez4509** [comment]
This site is complete. The content the client provided has been added and the site is responsive. Done
