### ISSUE TITLE
Credentials page images

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#20]
Some of those images take **way** too long to load. I inspected the 'bbb certificate' image and it's a 1406 x 1081 PNG that's being loaded as a 260 x 200. 

As a rule of thumb, never use PNG unless you need transparency effects (usually normal for logos). JPG is usually a much more size efficient option when it comes to images that have multiple colors. 

Please reassess all the images on this page (and all the other pages while you're at it) and resize them as necessary.

due:
1-5-16   4p

**Comment by rampage1213** [comment]
Done!
