### ISSUE TITLE
create new seal image

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#21]
![28years](https://cloud.githubusercontent.com/assets/539962/12246252/4cb993e6-b862-11e5-9502-1f20927f79c0.png)

This one is grammatically incorrect. "28th years in business" ...

Should've either been "28 years in business" or "28th year in business". 

Anyways, need you to make a brand new one that says "29 years in business" with no period at the end. Also, make another version with the same attributes but with NO dates at the bottom of the seal (the 1987 - 2015 part)

due:
1-12-16   3p

**Comment by jperez4509** [comment]
version 1:
![seal](https://cloud.githubusercontent.com/assets/8659273/12249576/6ad73ac8-b875-11e5-9f95-6e18c3c2c433.png)


version 2:
![seal-v2](https://cloud.githubusercontent.com/assets/8659273/12249582/7314da4c-b875-11e5-940e-332c3d49663b.png)

**Comment by jperez4509** [comment]
new version 1 (thicker number):
![seal](https://cloud.githubusercontent.com/assets/8659273/12273020/654507e0-b918-11e5-92d2-ef0a9d5b75e3.png)


new version 2 (thicker number:
![seal-v2](https://cloud.githubusercontent.com/assets/8659273/12273028/734f6dc6-b918-11e5-93db-53196d92a435.png)

**Comment by rodneystrong** [comment]
Hmm... 

Why is the "29" is different in both versions ?

**Comment by rodneystrong** [comment]
Thanks for answering @jperez4509   -___-) 

Anyways, no worries, client likes the seal. Well done
