### ISSUE TITLE
Final cleanup tasks from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#22]
Width -- Thank you for the video question.  Please make it all the same as the map as you did at the end of the video.

Borders -- let’s see what it looks like with a shading on the right and left borders -- use a rich color to compliment the site.

~~Font on the entire site - please make it darker -- halfway between its current state and bold. (We are thinking of our older clients…)~~

~~Add the 29th year stamp on the map.~~

~~Bottom footer with the contact info: Please align each of the three columns of info symmetrically.~~

Add the images of Paul and Chris (they're in the google drive: https://drive.google.com/drive/folders/0B2lLrPKhGIbrS1BUbDhGaVA2RUk)

due:
1-12-16  2p

**Comment by rampage1213** [comment]
Done!
