### ISSUE TITLE
Put seal onto map image

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#23]
https://drive.google.com/open?id=0B2lLrPKhGIbrLXJtYWl6MGYwa3c

If you look at the map on that link, you'll see where they placed the seal on the image (bottom right)

Once you've recreated the seal, put it on the map just like they have it in that link. Then upload it to the Drive for @rampage1213 to place on the site. 

due:
1-12-16   5p

**Comment by jperez4509** [comment]
@rodneystrong @rampage1213: I have added the seal to the map and uploaded the map to the google drive: https://drive.google.com/file/d/0B8EN2ZGYf3v5dldweWRCTmlFVVE/view?usp=sharing

![world-map-seal](https://cloud.githubusercontent.com/assets/8659273/12273345/43db4dba-b91a-11e5-8c24-9fdb9c4a848f.jpg)

**Comment by rampage1213** [comment]
Done!
