### ISSUE TITLE
Redo map

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#26]
According to client:

>Can you please make the 29 year stamp larger.  At 100% on Chrome, you cannot read the 1987-2016:

I'd say keep increasing it until the years are legible. 

due:
1-12-16   11p

**Comment by rampage1213** [comment]
Joel completed this and uploaded it to google drive. I have added this to the site.@rodneystrong @jperez4509

**Comment by rodneystrong** [comment]
Excellent work both of you. Thanks for handling this.
