### ISSUE TITLE
about page alignment issue

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#27]
![screen shot 2016-01-12 at 4 38 38 pm](https://cloud.githubusercontent.com/assets/539962/12281464/3e4c3752-b94b-11e5-8425-ee1003a7f6dc.png)

If you inspect the images, you'll notice that they're 2 different heights, that's why the horizontal alignment of the content is off. 

Fix the image heights, then the rest *should* be aligned. Always double-check though. God knows how many times I've been wrong..

due:
1-12-16    8p

**Comment by rampage1213** [comment]
I fixed this issue here: Hopefully the last edits #25, Done!
