### ISSUE TITLE
Definitely the last edits from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#28]
From the client: 

>The site looks great.  Looks like you made all the requested changes except for the density issue.  Please go live when you can – you can always deal with the density issue after.
 
We reviewed the testimonials again and have the following three changes which got by us before:
 
 
1)    Remove the last name “Leslie” in the below quote: 

 
![les](https://cloud.githubusercontent.com/assets/539962/12311863/14409fec-ba0f-11e5-933e-e220243d2651.jpg)

 
 
2)    Remove the last name “Deidrick” in the below quote:

 
![diane](https://cloud.githubusercontent.com/assets/539962/12311867/180b7cc8-ba0f-11e5-84de-0cd49edb26f6.jpg)

 
 
3)    Replace the actual images for the above two testimonial with the images in the attached PDF.

 
[Revised Client Testimonial letters (2) to Buildicus 1-13-2016.pdf](https://github.com/EditLLC/client-estate-research/files/89678/Revised.Client.Testimonial.letters.2.to.Buildicus.1-13-2016.pdf)

 
Lastly, on Chris’ bio, he requests this change:  change “water sports” to sports. 
 
 
Thank you for all your good work!

due:
1-13-16   10p

**Comment by rampage1213** [comment]
Done!
