### ISSUE TITLE
Change Logo

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#3]
Please recreate this by: 

1) Make "Estate Research Associates" small caps with the first letter of each word being large caps

2) Make "Private Investigation Firm" initial caps 

3) export as png again and try to keep the same width/height if possible

Please upload the image to the google drive once you've uploaded it. 

due:
12-26-15     6p

**Comment by jperez4509** [comment]
![estate-research-logo](https://cloud.githubusercontent.com/assets/8659273/11968483/84363ece-a8c1-11e5-9bc4-2c3138ef2594.png)


I also have an ai and pdf file. The image above is a white logo, hopefully you can see it.

**Comment by rodneystrong** [comment]
Excellent work sir. Thank you for getting this so early. I'm going to have Quintin implement this in another task.

**Comment by rodneystrong** [comment]
Please upload the png, ai, and pdf files to our google drive.

**Comment by jperez4509** [comment]
Done. https://drive.google.com/folderview?id=0B0GRwzxO60XiM2p2TUgxSkxnalk&usp=sharing

**Comment by rodneystrong** [comment]
Crap, actually you did this wrong. "A Private Investigation Firm" is supposed to be in INITIAL caps, meaning only the first letter of each word is capitalized. 

Please redo-this and replace all the incorrect versions into the google drive.

due:
1-6-16    6p

**Comment by jperez4509** [comment]
![estate-research-logo](https://cloud.githubusercontent.com/assets/8659273/12135977/df3c33c8-b3f7-11e5-8cfb-8d4a88e0c51b.png)

I have updated all version in the Google Drive

**Comment by rampage1213** [comment]
@rodneystrong I saw this issue and already updated pushed it
.

**Comment by rodneystrong** [comment]
@jperez4509 nooooooo duuuuuude   T__T)   Initial caps means to just capitalize the first letter.. Not small caps.. 

Notice how you have the top line "Estate Research" in small caps? You did the same thing for the line below.. 

No biggie, just redo the logo again, but use initial caps for the bottom line "A Private Investi.." 

Initial caps means the *first letter of the word* is capitalized and the *rest of the word* is lower cased.

**Comment by rodneystrong** [comment]
@rampage1213 thanks for being on top that. Unfortunately the logo was wrong :'(   But please by all means upload and push the next one that Joel creates.

**Comment by jperez4509** [comment]
Okay. Let's try this again.

![estate-research-logo](https://cloud.githubusercontent.com/assets/8659273/12178463/71fc2bf8-b526-11e5-9a55-6873568fe70e.jpg)

**Comment by jperez4509** [comment]
Files have also been updated in the google drive.

**Comment by rodneystrong** [comment]
Good job dude. That's correct. 

However, one last issue. When you crop these images, can you please crop right to the edge of the image? When you don't, then this becomes an issue: 

![screen shot 2016-01-07 at 3 07 53 pm](https://cloud.githubusercontent.com/assets/539962/12185577/9f27e1e2-b550-11e5-9adb-24f645e187b2.png)

Please recrop. In photoshop, there should be an option to "snap to" the sides in order to get as close as possible to the edge.

**Comment by jperez4509** [comment]
@rampage1213 Image has been cropped and added to Google Drive, again.

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Perfect
