### ISSUE TITLE
Download the current live site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#30]
Again, HTTTrack to the rescue. Here's the drive link: https://drive.google.com/open?id=0B88_mCI0OTGkOVE4TEV2ejNWdm8

http://estateresearch.com/

due:
1-14-16   11:30a

**Comment by rodneystrong** [comment]
updating due date time cause need this done earlier in the day in order to launch new site design.

**Comment by rampage1213** [comment]
Done!
