### ISSUE TITLE
Top hero image text

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-estate-research#4]
http://somup.com/colDVV3Vv

Remember, push all changes to gh-pages as well. 

due:
12-16-18    5p

updated due:
12-26-15    3p

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Nice job on getting the effect. Also good job on maintaining it on resize. Glad you remembered that. 

 I looked at the code and noticed you used the ````<h1>```` tag twice though. That's still a less than stellar coding choice in terms of semantics (https://www.google.com/search?q=html+semantics&oq=html+semantics&aqs=chrome..69i57.3463j0j1&sourceid=chrome&es_sm=91&ie=UTF-8) and SEO. I do like how you used pseudo-selectors to target and get your effect. Pretty crafty. However I'll need you to change your second h1 tag into an h2. So specifically the h1 tag surrounding the words "Paul Elissiry & Chris Larsgaard, Private Investigators" needs to become an h2. 

Don't forget to double-check to make sure it's still responsive and lines up correctly with the text. 

updated due:
12-26-15  3p

**Comment by rampage1213** [comment]
Done! quick fix just had to change 
```
.jumbotron h1:last-child {

}
```
to
```
.jumbotron h2 {

}
```
Still responsive
